### ISSUE TITLE
Background color only works on last button

### ISSUE THREAD

**Issue by cozyGalvinism** [kepler155c/opus#11]
Tested on the develop-1.8 branch, when I define 2 buttons like this:

```
local mainPage = UI.Page {
    perimeterBtn = UI.Button {
        text = 'Perimeter',
        x = 2,
        y = 4,
        action = 'perimeter',
        backgroundColor = colors.lime
    },
    quarryBtn = UI.Button {
        text = 'Quarry',
        x = 2,
        y = 2,
        action = 'quarry',
        backgroundColor = colors.lime
    }
}
```
the perimeter button gets the background color (but only the perimeter button):
![image](https://user-images.githubusercontent.com/1332113/59968803-138d8c80-9540-11e9-9b6c-af223f3f6139.png)

If I, however, place the quarry button under the perimeter button (position-wise):

```
local mainPage = UI.Page {
    perimeterBtn = UI.Button {
        text = 'Perimeter',
        x = 2,
        y = 4,
        action = 'perimeter',
        backgroundColor = colors.lime
    },
    quarryBtn = UI.Button {
        text = 'Quarry',
        x = 2,
        y = 6,
        action = 'quarry',
        backgroundColor = colors.lime
    }
}
```
then the quarry button gets the background color (again, only the quarry button):
![image](https://user-images.githubusercontent.com/1332113/59968814-6404ea00-9540-11e9-81b7-267a385bb542.png)

Unless I'm doing something wrong, I think this isn't intended.

**Comment by cozyGalvinism** [comment]
Ah, I see. It's focusing the first button right away, so the original color is overriden. Welp, should've looked better, sorry.

**Comment by kepler155c** [comment]
> Ah, I see. It's focusing the first button right away, so the original color is overriden. Welp, should've looked better, sorry.

FYI - you can also set focusIndicator = '>' (or some char) to denote focus instead of having the color change.

**Comment by cozyGalvinism** [comment]
Oh that's neat! Thanks for that!
