### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by makjak** [kepler155c/opus#12]
Hello , I have the new develop version 1-8 (after updating the old one) and now I am trying to update to the last one and I receive an error.
[string "git"]:26 Failed to download https://api.github.com/kepler155c/opus/git/trees/develop-1.8?recursive=1

Is there any fix?

**Comment by kepler155c** [comment]
That will happen occasionally if there has been too many calls to github within an hour. You, most likely, need to wait for 10 mins or so and try again.

If you have a github API key, you can set it in lua before running the update. You would paste into lua this type of command:

_G._GIT_API_KEY='YOURKEY'

**Comment by makjak** [comment]
Great I done it with my api key...
Your work is great.. and I appreciate your help

**Comment by kepler155c** [comment]
Excellent - and thanks !
