### ISSUE TITLE
Installer error

### ISSUE THREAD

**Issue by PanSzelescik** [kepler155c/opus#2]
![image](https://user-images.githubusercontent.com/26679785/47968171-4b55cb80-e066-11e8-9471-ba30a92f2c19.png)

**Comment by kepler155c** [comment]
There are several reasons why this may have occurred.
1. Github may be having some issues.
2. You may have exceeded the number of requests you can make per hour. I see this quite a bit and after waiting a few minutes, the connection should work again.

I have made a new Package program in the develop-1.8 which greatly reduces the number of calls I make to Github Hopefully, those changes will prevent the type of error you received.
