### ISSUE TITLE
Milo Crash after clearing search, editing min/max,   1.8 Dev

### ISSUE THREAD

**Issue by rangerdude** [kepler155c/opus#24]
This happens on Remote and local Milo.

When you back space to clear the last thing you searched for it gives an error of:

MiloRemote.lua:250 attempt to get length of field 'filter' (a null value).

On Milo it self the error is:
MiloLocal.lua:229 listing.lua:276 attempt to get length of field 'filter' ( a null valre)

**Comment by rangerdude** [comment]
I know now that this should have been put under opus-apps.
Since I started it here I will just put the info on this issue and not open one on opus-apps.


RemoteMilo.lua line 250 is:
```
if #self.filter == 0 then
	self.filter = nil
end
```


Should be unless there is something I am missing with the # sign.
```
if self.filter == 0 then
	self.filter = nil
end
```

I will look at the RemoteLocal.lua and update the info on the fix.

**Comment by rangerdude** [comment]
> I know now that this should have been put under opus-apps.
> Since I started it here I will just put the info on this issue and not open one on opus-apps.
> 
> RemoteMilo.lua line 250 is:
> 
> ```
> if #self.filter == 0 then
> 	self.filter = nil
> end
> ```
> 
> Should be unless there is something I am missing with the # sign.
> 
> ```
> if self.filter == 0 then
> 	self.filter = nil
> end
> ```
> 
> I will look at the RemoteLocal.lua and update the info on the fix.

Looks like it is the same issue in listing.lua  /packages/milo/core/

Fix is just removing the # from
if #self.filter             line 276 of listing.lua.

**Comment by kepler155c** [comment]
Please try updating Opus (System->Update) and also the milo package. I think this has been addressed previously.

**Comment by rangerdude** [comment]
> Please try updating Opus (System->Update) and also the milo package. I think this has been addressed previously.

I have had this Milo setup for a while. It is updated to the latest Dev. But I ran into more errors. So I am going to redo it from fresh install.  I will update or close the issue once I am done.

**Comment by rangerdude** [comment]
Found another issue upon fresh install.
With the # sign being an issue.  I don't think LUA uses # for a var.  But you guys may know for sure.


Machines.lua   line 146
----
if self.filter.value and #self.filter.value > 0 then
----
MiloLocal.lua:	if context.storage:isOnline() and #context.queue > 0 then
----

**Comment by xAnavrins** [comment]
Came on the server you were playing and helped you fix up some stuff in your setup, one had in fact an outdated version, and the error seemed to be fixed after updating it.
A fresh OpusOS install will not update the packages that were previously installed, that might be why it was still having errors, make sure to use the Package app and click "Update All" as well.

Let us know if anything else breaks.
