### ISSUE TITLE
Opus crash on turtles after updating to 1.8-develop

### ISSUE THREAD

**Issue by jakedacatman** [kepler155c/opus#25]
after updating a turtle to the latest develop release, opus crashes with the error "kernel.lua:300: 6.tl3.lua: Unable to find module pathfind"

copying pathfind.lua from an older version of opus also results in a crash (kernel.lua:300: pathfind.lua:1: Unable to find module jumper.grid)

updating the turtle package before updating the base os results in the original error

**Comment by jakedacatman** [comment]
copying pathfind.lua from an older version of opus also results in a crash (kernel.lua:300: pathfind.lua:1: Unable to find module jumper.grid)

**Comment by kepler155c** [comment]
You can safely delete sys/init/6.tl3.lua - this file was moved into the turtle package. I have made an update to remove that file on subsequent upgrades.

**Comment by Nerdpie** [comment]
I ran into some issues updating Opus, but the biggest issue was that I didn't pay attention to the free space on the computer.  I ended up deleting the old `/sys` directory on my neural, and a few others on my Milo turtle.  May be worth checking!

**Comment by jakedacatman** [comment]
that works as a fix but the update now works
