### ISSUE TITLE
Compacted Install

### ISSUE THREAD

**Issue by Nerdpie** [kepler155c/opus#26]
While I haven't worked with GitHub Actions myself, would it be practical (I'm sure it's possible, but the feasibility and added support work I do not know) to have a script set up to automatically minify and compress Opus?  I know that would make it harder to modify in-game, but every byte helps, especially if I actually set up Milo to handle every recipe in a pack like Enigmatica 2: Expert.  Ideally, both versions would still be available based on user interest (the minified code _should_, in theory, be functionally the same), similarly to libraries like jQuery having the regular and `-min` versions available.

**Comment by kepler155c** [comment]
That does sound like a good idea. Also, there are some other options currently available:

1. lzwfs package will perform compression to specified directories (set in System->System)
2. minify package can be install and run against the sys directory.

Note that both of these are still somewhat experimental (but I have not seen any negatives so far).

**Comment by Nerdpie** [comment]
Yeah, I've started using the lzwfs package; I think that it was part of what brought about this suggestion, actually.
