### ISSUE TITLE
Chest is missing #2 The chest strikes again

### ISSUE THREAD

**Issue by k4io** [kepler155c/opus#49]
Hello, I am having a very similar issue to: https://github.com/kepler155c/opus/issues/6 

I installed plethora and everything worked fine on single player but when I go back to the public server  where it is not installed I get the error about not being on-top of the chest. There is a chest underneath, I am on FTB Revelation.

If you could help I would appreciate it.

**Comment by xAnavrins** [comment]
You kind of answered yourself there.
Unfortunately the builder app does require either Plethora (MC1.12), or CC:Tweaked 1.94.0 (MC1.15 and 1.16 only), those allow a greater manipulation of chests and inventories which is required for it to work.

**Comment by k4io** [comment]
Ah ok that's a shame, there doesn't seem to be any other builders out there at the moment. The pack has a lower version of CC:Tweaked unfortunately.

Thanks anyway.
