### ISSUE TITLE
Computercraft pastebin bug fix in app store

### ISSUE THREAD

**Issue by yesseruser** [kepler155c/opus#52]
**Is your feature request related to a problem? Please describe.**
The app store does not work when downloading.

**Describe the solution you'd like**
The app store could run this code in the folder it does pastebin if it didn't already: 
``` lua
local r = http.get("https://pastebin.com/raw/jCfCfBPn​")
local f = fs.open( shell.resolve( "pastebin" ), "w" )
f.write( r.readAll() ); f.close(); r.close()
```
This code creates a new Pastebin file that runs instead of the ROM one.
Here is where this code is from: [Youtube](https://www.youtube.com/watch?v=MkloBnl-W8s)

**Describe alternatives you've considered**
The installer could do this.

**Comment by xAnavrins** [comment]
I can't replicate this, apps download fines without changing anything, and our pastebin downloader is already adjusted for that change.
Apps in the AppStore are all third party, so if they themselves use the old way of downloading from pastebin, there's nothing we can do on our side.
