### ISSUE TITLE
Invalide package when try to install from package manager

### ISSUE THREAD

**Issue by mrsolarius** [kepler155c/opus#56]
**Describe the bug**
After the first installation during de welcome process, when I try to install a package with package manager I have this error : 
```
pakage.lua:60: Invalid package
```

**To Reproduce**
1. Install OS with this command : `pastebin run UzGHLbNC`
2. After the first install, reboot computer
3. When package manager step arrive, try to install one package

**Expected behavior**
I expect the package to be installed

**Versions**
What version of Minecraft, CC:Tweaked, Plethora (if applicable), Opus branch are you using
 - MC : 1.12.2
 - CC:T : 1.88
 - Opus : master-1.8

**Comment by xAnavrins** [comment]
>Opus : master-1.8

Please use the develop-1.8 branch as it is the most up to date version, the master branch is out of date and its package manager is currently broken.

**Comment by Impre-visible** [comment]
I have the same error, but with the develop-1.8 branch, we have a lot of error, we cant open a program

**Comment by Impre-visible** [comment]
version.lua have some problem line 15, and he need more space

**Comment by mrsolarius** [comment]
In my case I have test in the develop branch and yes it works.
@Impre-visible I think It could be useful to provide more information ;)

**Comment by Kan18** [comment]
> version.lua have some problem line 15, and he need more space

should this issue be left open? it sounds like @Impre-visible was just out of disk space here

**Comment by Impre-visible** [comment]
yeah for sure, don't have to reopen the issue :D
