### ISSUE TITLE
Chest is missing

### ISSUE THREAD

**Issue by KrysRobyns** [kepler155c/opus#6]
Hello Kepler.

First, let me thank you for this perfect OS.

I tried few weeks ago building schematics using yor OS and it worked perfectly.
Unfortunatly, I deleted the whole save, including my perfect mining turtle.

Today I reinstalled Opus Os with Builder & core package. I tried to build some schematics but, each time, I have an issue.
Turtle say : **Builder.lua:748: A chest or ME interface must be below turtle**.

I tried and tried. Using new fresh map, removing lots of mods... Nothing work...

I'm on MC 1.12.2 and up-to-date CC & Opus Os.
The chests you can see on screenshot are from Draconic Evolution and already worked with turtle before. (I also trie with vanilla chests) and i tried each side of turtle.
Could you please help me to resolve this issue ?

Thanks.

Krys
![2019-03-26_12 43 12](https://user-images.githubusercontent.com/24703834/54994982-f4757200-4fc5-11e9-92a3-0e76e9539d10.png)

**Comment by kepler155c** [comment]
I cannot tell from the screenshot - but is there a chest below the turtle ? Also, what branch did you select when you installed Opus ?

Please try a vanilla chest below turtle first - if that works, then try the draconic chest again.

Thanks

**Comment by KrysRobyns** [comment]
Thanks for the reply.

Yes, there is a chest below the turtle.

I relaunched a fresh install of Opus OS.
Master 1.8+ Stable.
reboot
Core package
reboot
Builder package
reboot
Vanilla chest below the turtle...
Same issue.
![2019-03-26_15 39 13](https://user-images.githubusercontent.com/24703834/55006473-1d096600-4fde-11e9-820e-6314e67ee23b.png)
![2019-03-26_15 39 27](https://user-images.githubusercontent.com/24703834/55006474-1d096600-4fde-11e9-8d81-23912005501d.png)

**Comment by kepler155c** [comment]
I believe this might be due to using vanilla ComputerCraft instead of CC:Tweaked. CC:Tweaked provides the ability to use chests, etc as peripherals.

[(https://github.com/SquidDev-CC/CC-Tweaked)] The mod is also available on Curse.

If you are already using CC:Tweaked, give this a try in lua: peripheral.wrap('bottom')
A table should be returned.

**Comment by KrysRobyns** [comment]
So...

Indeed, and I don't have any f***** idea why, ... I remember I was using CC:Tweaked when it worked fine.

But, still the same issue with it now...
I didn't understand your last words about peripheral.wrap('bottom'). Please have a look on the screenshoots to tell me if it's what you need.
![2019-03-26_17 55 52](https://user-images.githubusercontent.com/24703834/55017419-f6085f80-4ff0-11e9-8baf-f6bf8833f324.png)
![2019-03-26_17 54 19](https://user-images.githubusercontent.com/24703834/55017420-f6a0f600-4ff0-11e9-908d-8430d37ea406.png)

**Comment by KrysRobyns** [comment]
I aslo noticied that the first time it worked, I had a "builder" icon in the Apps tab. 
Right now, I don't have it...

**Comment by KrysRobyns** [comment]
Finally !
I found why !

The Plethora Mod was missing.
Now it works so fine !

Again, thank your for replying and of course for this awesome OS !

![2019-03-26_23 30 36](https://user-images.githubusercontent.com/24703834/55038287-9e81e800-5020-11e9-93d7-185576d38b0a.png)

**Comment by kepler155c** [comment]
Glad it's resolved - have fun!
