### ISSUE TITLE
Unstable 1.8 Booting to monitor?

### ISSUE THREAD

**Issue by caza1516** [kepler155c/opus#7]
Hey Kepler, been using milo with opus and have encountered a bug. If you have any type of monitor set up with milo, such as the crafting monitor when you reboot the turtle it boots to the screen instead of booting to the turtle.
I'm using the latest Unstable 1.8 build.
[Screenshot](https://imgur.com/a/wglKh8x)

**Comment by kepler155c** [comment]
It may be that you are booting into Opus Kiosk mode - make sure to select normal Opus on startup.

**Comment by caza1516** [comment]
That sorted it :)
